config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :line_items
  resources :carts
  resources :artworks
  get 'artists', to: 'artworks#artists'
  post 'index', to: 'artist_roles#create', as: 'artist_role'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'artworks#index'
end

app/models/artwork.rb
class Artwork < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    has_one_attached :artwork_image
    has_many :line_items

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
    before_action :authenticate_user!, except: %i[index]
    before_action :check_auth
    before_action :find_artwork, only: %i[show edit update destroy]

    def index
        @artworks = Artwork.order(:created_at)
    end

    def show; end

    def new
        @artwork = Artwork.new
    end

    def create
        artwork = Artwork.create(artwork_params)
        redirect_to artwork
    end

    def edit; end

    def update
        @artwork.update(artwork_params)
        redirect_to @artwork
    end

    def destroy
        @artwork.destroy
        redirect_to artworks_path
    end

    def artists
        @artworks = Artwork.order(:artist)
    end

  private

    def check_auth
        authorize Artwork
    end

    def find_artwork
        @artwork = Artwork.find(params[:id])
    end

    def artwork_params
        return params.require(:artwork).permit(:title, :artist, :description, :price, :artwork_image)
    end
end

app/helpers/artwork_helper.rb
module ArtworkHelper
end

app/views/artworks/_form.html.erb
<%# Below, calls to the artwork entity through the artwork model, to allow input from the %>
<%# end-user, to update the data in the artwork database, through the use of forms %>
<center>
  <%= form_with(model: @artwork) do |f| %>
    <% if @artwork.artwork_image.attached? %>
      <fieldset>
        <%= cl_image_tag @artwork.artwork_image.key, aspect_ratio: "1:1", background: "#f4f1e0", border: "5px_solid_rgb:bce8e6", gravity: "auto", height: 233, radius: "max", width: 200, crop: "fill", cloud_name: 'cozybaker' %>
      </fieldset>
    <% end %>
    <fieldset class="mb-2">
      <%= f.label :artwork_image %>
      <%= f.file_field :artwork_image %>
    </fieldset>
    <fieldset class="mb-2">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </fieldset>
    <fieldset class="mb-2">
      <%= f.label :artist %>
      <%= f.text_field :artist %>
    </fieldset>
    <fieldset class="mb-2">
      <%= f.label "$" %>
      <%= f.number_field :price, in: 1.0..10000.0, step: 0.5 %>
    </fieldset>
    <fieldset>
      <%= f.label :description %><br>
      <%= f.text_area :description, size: "70x5" %>
    </fieldset>
    <fieldset class="mb-2">
      <%= f.submit class: 'btn btn-success' %>
    </fieldset>
  <% end %>
</center>

app/views/artworks/artists.html.erb
<div>
  <%= link_to('Back', root_path, class: 'btn btn-outline-dark') %>
</div>
<h1 class="text-center" style="color:#4c301e;">All Artists</h1>

<%# Below is calling data from the artwork entity, through the artworks model, to display the list of artists %>
<%# in alphbetical order %>
<center>
  <div class="card-deck" style="display: flex; flex-wrap: wrap; justify-content: center;">
    <% @artworks.each do |artwork| %>
      <div class="card" style="width: 30rem; color:#4c301e; background:#f4f1e0;">
        <div class="card-body">
          <h5 class="card-title"><%=artwork.artist%></h5>
          <span>
            <%= link_to('View', artwork, class: 'btn btn-outline-dark stretched-link') %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</center>

app/views/artworks/edit.html.erb
<%# Calling to artwork entity, to display the artwork title selected by the end-user %>
<h1 class="text-center" style="color:#4c301e;">Edit <%= @artwork.title %> </h1>
<%= render 'form' %>

app/views/artworks/index.html.erb
<h1 class="text-center" style="color:#4c301e;">All Artwork</h1>

<%# Below calls to the artwork entity, via the artwork model, iterating over the values to  %>
<%# display the image, title and price of all the artwork in the database. %>
<center>
  <div class="card-deck" style="display: flex; flex-wrap: wrap; justify-content: center;">
    <% @artworks.each do |artwork| %>
      <div class="card" style="width: 30rem; color:#4c301e; background:#f4f1e0;">
        <div class="card-body">
          <%= cl_image_tag artwork.artwork_image.key, crop: :scale, width: 300, height: 400, cloud_name: 'cozybaker' %>
          <h5 class="card-title"><%=artwork.title%></h5>
          <h5 class="card-title"><%=number_to_currency artwork.price%></h5>
          <span>
            <%= link_to('View', artwork, class: 'btn btn-outline-dark stretched-link') %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</center>

app/views/artworks/new.html.erb
<center>
  <h1 style="color:#4c301e;">Add Artwork</h1>
</center>
<%= render 'form' %>

app/views/artworks/show.html.erb
<div>
  <%= link_to('Back', root_path, class: 'btn btn-outline-dark') %>
</div>

<div>
  <h1 class="text-center" style="color:#4c301e;"> <%= @artwork.title %> </h1>
  <h4 class="text-center" style="color:#4c301e;">By <%= @artwork.artist %> </h4>
</div>

<%# Below calls to the artwork entity, via the artwork model, to display  %>
<%# all the data of a specific artwork, chosen by the end user. %>
<div class="text-center" style="display: flex; justify-content: center;">
  <div class="card-deck" style="display: flex; flex-wrap: wrap;">
    <%= cl_image_tag(@artwork.artwork_image.key, crop: :scale, width: 500, cloud_name: 'cozybaker') if @artwork.artwork_image.attached? %>
    <div class="card" style="width: 30rem; height: 20rem; color:#4c301e; background:#f4f1e0;">
      <div class="card-body">
        <h5 class="card-title text-center">Description</h5>
        <p class="card-title text-center" style="padding: 5rem"><%=@artwork.description%></p>
        <%= button_to('Add to Cart', line_items_path(artwork_id: @artwork), class: 'btn btn-outline-success') %>
      </div>
    </div>
  </div>
</div>
<h2 class="text-center mt-4" style="color:#4c301e;"> <%= number_to_currency @artwork.price %> </h2>
<% if policy(@artwork).edit_or_destroy? %>
  <div class="btn-toolbar m-5" style="display: flex; justify-content: center;">
    <%= link_to('Edit', edit_artwork_path(@artwork), class: 'btn btn-warning me-4') if policy(@artwork).edit? %>
    <%= button_to('Delete', @artwork, class: 'btn btn-danger', method: :delete, form: { data: {turbo_confirm: "Are you sure you want to delete '#{@artwork}'?" } }) if policy(@artwork).destroy? %>
  </div>
<% end %>