config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :line_items
  resources :carts
  resources :artworks
  get 'artists', to: 'artworks#artists'
  post 'index', to: 'artist_roles#create', as: 'artist_role'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'artworks#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

 
# Calling to the line_items entity, via the line_item model to display
# the artwork data added by the end-user into the cart.
    def add_artwork(artwork)
        current_item = line_items.find_by(artwork_id: artwork.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(artwork_id: artwork.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invaild_cart
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Cart is now empty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invaild_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="continue-shopping pv1 mt4 has-text-right">
  <%= link_to 'Continue Shopping', artworks_path, class: 'btn btn-outline-dark' %>
</div>
<h1 class="text-center" style="color:#4c301e;">Shopping Cart</h1>

<%# Below calls to the cart and line_items entities, via the cart and line_item models, to display what has been added to the cart  %>
<%# via the line_items entity. %>
<section class="section">
  <%= render(@cart.line_items) %>
<hr/>
  <div class="columns" >
    <div class="column" style="display: flex; justify-content: flex-start;">
      <%= button_to('Empty Cart', @cart, class: 'btn btn-danger', method: :delete, form: { data: {turbo_confirm: "Are you sure you want to empty cart?" } }) %>

<%# Below, calls to the cart model to get the total_price method, which calls the total_price method %>
<%# from the line_item model, adding up the price of each artwork put into the cart. %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4" style="display: flex; justify-content: flex-end;">
        <spanc class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>