config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :line_items
  resources :carts
  resources :artworks
  get 'artists', to: 'artworks#artists'
  post 'index', to: 'artist_roles#create', as: 'artist_role'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'artworks#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digital Art Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/artworks" style="color:#4c301e;">DA Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="/artworks">Home</a>
            <a class="nav-link" href="/artists">Artists</a>
            <a class="nav-link disabled"></a>
            <% if user_signed_in? %>
              <%= link_to('Sell Artwork', new_artwork_path, class: "btn btn-outline-success") if policy(Artwork).new? %>
            <% end %>
          </div>
        </div>
        <% if cart_has_items %>
          <%= link_to cart_path(@cart), class:"navbarr-item button is-warning" do %>
            <span class="icon is-small">
              <i class="fa fa-shopping-cart"></i>
            </span>
            <span>Cart
              <%= cart_count_over_one %>
            </span>
          <% end %>
        <% end %>
        <% if user_signed_in? %>
          <div class="btn btn=toolbar p-3">
            Signed in as, <%= current_user.email %>
          </div>
          <% if current_user.has_any_role?(:artist, :admin) %>
            <%= "" %>
          <% else %>
            <div class="btn btn=toolbar p-3">
              <%= button_to 'Become an Artist', artist_role_path, class: 'btn btn-outline-success', method: :post if policy(Artwork).artist_roles? %>
            </div>
          <% end %>
          <div class="btn btn=toolbar p-3">
            <%= button_to 'Logout', destroy_user_session_path, class: 'btn btn-outline-primary', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out?" } } %>
          </div>
        <% else %>
          <div class="btn btn=toolbar">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-secondary' %>
          </div>
          <div class="btn btn=toolbar p-3">
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary' %>
          </div>
        <% end %>
      </div>
    </nav>
    <style>
      body {
        background: #f4f1e0;
      }
    </style>
  </head>
  <body>
    <main class= "p-3">
      <% if notice%>
        <p class="alert alert-info notice" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>